# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm init -y
      - npm install express
 
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
     
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - npm run server.js
  post_build:
    commands:
      - echo Build completed on `date`
      - node server.js
# Include only the files required for your application to run.
artifacts:
  files:
    - server.js
    - package-lock.json
    - Dockerfile
    - package.json
    - node_modules/**/*
