version: 0.2

phases:
  install:
    runtime-versions:
     
      nodejs: 10
  build:
    commands:
      
      - echo Building the Node code...
     
artifacts:
  secondary-artifacts:
   
    nodejs_artifacts:
      base-directory: 
      files:
        - server.js
        - package.json
        - node_modules/**/*
